### ISSUE TITLE
Enhance RootPythia resiliency

### ISSUE THREAD

**Issue by ctmbl** [iScsc/RootPythia#49]
- [ ] Handle more status code #28 #41 #42 
- [ ] Deal with unexpected known exceptions #32 
- [ ] Reduce RateLimiter requests timeout not to trigger discord.gateway timeout #50 
- [ ] rework `on_ready` function
